# Generated by Django 3.0.6 on 2021-09-16 14:04

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Kod pocztowy jest wymagany w formacie XX-XXX', regex='^(^[0-9]{2}(?:-[0-9]{3})?$|^$)')])),
                ('street', models.CharField(max_length=15)),
                ('house_number', models.CharField(max_length=3)),
                ('flat_number', models.CharField(default='0', max_length=3)),
                ('phone_number', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.FloatField(validators=[api.validators.validate_rating_number])),
            ],
        ),
    ]
